---
title: "Math E-23C Term Project"
subtitle: "An analysis of the Lakers 2019 Championship season"
author: "Maria Cristina An, Daniel Lebedinsky, Julio Solis Arce"
date: "`r format(Sys.time(), '%d %B, %Y')`"
abstract: "The current documents offers a short summary of the analysis our team did  on the LA Lakers 2019 NBA championship campaign. First we provide a short motivation for our study. Then, we introduce the dataset. Finally, we describe the main findings of our analysis."
output:
  pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Motivation

Los Angeles Lakers is one of the most recognized sports franchise around the world. They are the basketball team with the most fans with around 22 million.^[https://bolavip.com/en/nba/The-25-NBA-teams-with-most-fans-20200423-0002.html]. According to recent polls, 44% of Americans have a positive opinion of the team and 87% of recognize the name of the team (ranking number 2 in both categories, only below Chicago Bulls).^[https://today.yougov.com/ratings/sports/fame/basketball-teams/all].

The season 2019-20 proved to be a very important season for LA Lakers. First, it was a season when playoffs were suspended due to COVID. Then, the season was also relevant due to the death of Kobe Bryant, Lakers world-known star. Whatever these circumstances, Lakers won the NBA Western Conference title and the NBA championship with a record of 52 wins against 19 loses.

The present data analytic exercises investigates the successful and historic campaing of the Lakers. 

## Data set

The data set that we use for our analysis contains the 92 games that Lakers played during the season.^[Available here: https://www.basketball-reference.com/teams/LAL/2020/gamelog/] This game log has as observations every single game of the season including the regular season, the playoffs and the final against Miami. As variables the data set is exhaustive in recording the details of the game from both teams: we have data on points scored, goal attempts, goal percentage, number of goals and type of goals (field, 3-point, free throw), rebounds, steals, blocks, turnovers and fouls. 

## Main results

- Result 1

- Result 2

- Result 3